name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current branch name
        id: get_branch_name
        run: |
          # Extract branch name from GITHUB_REF
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/heads\///')
          echo "Current branch: ${BRANCH_NAME}"
          # Save branch name to GitHub Actions environment variable
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run create-infrastructure workflow
        id: create_infrastructure
        run: |
          RUN_ID=$(gh run list --json databaseId --workflow= Create_infrastructure_only_Terraform_back --limit 1 | jq -r '.[0].databaseId')
          gh run watch $RUN_ID --exit-status